name: Bump packages
description: Bump (update) Homebrew outdated packages
author: SMillerDev
branding:
  icon: arrow-up-circle
  color: yellow
inputs:
  token:
    description: GitHub token (not the default one)
    required: true
  formulae:
    description: Formula names, space-separated
    required: false
    default: ''
  casks:
    description: Cask names, space-separated
    required: false
    default: ''
  fork:
    description: Use a fork when opening a PR
    required: false
    default: ${{ github.repository_owner != 'Homebrew' }}
outputs:
  pr-urls:
    description: "URLs of opened PRs, they are space-separated"
    value: ''
  pr-numbers:
    description: "Numbers of opened PRs, they are space-separated"
    value: ''
runs:
  using: composite
  steps:
    - name: Bump formulae
      run: |
        if [[ "$INPUT_FORK" == "true" ]]; then
          NO_FORK=""
        else
          NO_FORK="--no-fork"
        fi
        IFS=" " read -r -a formulae <<<"${INPUT_FORMULAE}"
        brew bump $NO_FORK --open-pr --formulae "${formulae[@]}" >> bump.log
      shell: bash
      if: inputs.formulae != ''
      env:
        INPUT_FORMULAE: ${{ inputs.formulae }}
        INPUT_FORK: ${{ inputs.fork }}
        HOMEBREW_DEVELOPER: "1"
        HOMEBREW_GITHUB_API_TOKEN: ${{ inputs.token }}
    - name: Bump casks
      run: |
        if [[ "$INPUT_FORK" == "true" ]]; then
          NO_FORK=""
        else
          NO_FORK="--no-fork"
        fi
        IFS=" " read -r -a casks <<<"${INPUT_CASKS}"
        brew bump $NO_FORK --open-pr --casks "${casks[@]}" >> bump.log
      shell: bash
      if: inputs.casks != ''
      env:
        INPUT_CASKS: ${{ inputs.casks }}
        INPUT_FORK: ${{ inputs.fork }}
        HOMEBREW_DEVELOPER: "1"
        HOMEBREW_GITHUB_API_TOKEN: ${{ inputs.token }}
    - name: Set outputs
      id: set_outputs
      shell: bash
      run: |
        all_urls=$(cat bump.log | grep -o 'https://github.com/.*/pull/[0-9]*' | tr '\n' ' ')
        if [[ -z "$all_urls" ]]; then
          echo "No PRs were created."
        else
          all_numbers=$(echo "$all_urls" | grep -o 'pull/[0-9]*' | sed 's/pull\///g' | tr '\n' ' ')
          echo "pr-urls=$all_urls" >> $GITHUB_OUTPUT
          echo "pr-numbers=$all_numbers" >> $GITHUB_OUTPUT
        fi
